## provSyn1589828.R

## Creating provenance for the PIK3CA mutation indicator as
## provided by CBIO

## GET ENTITY
pik3caEnt <- getEntity('syn1589828')

## CREATE ACTIVITY
activity <- Activity(list(name = 'Downloaded from CBIO (http://bit.ly/V8QrLZ)'))
activity <- storeEntity(activity)

## GENERATED BY
generatedBy(pik3caEnt) <- activity
pik3caEnt <- storeEntity(pik3caEnt)